### ISSUE TITLE
Add Cloud Name "vendor" to all unattached scripts

### ISSUE THREAD

**Issue by donaldgheen** [rs-services/cos_assets#10]
Megan Crandell [3:32 PM] 
Would it be possible to tweak the UAV script to also pull cloud vendor? We’re splitting the COA template up by vendor and this is one area where we don’t (afaik) have a way to know which vendor to attribute the savings to

**Comment by tusharshahrs** [comment]
Cloud Vendor has been added to unattached volumes and merged
